# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Compile with Maven

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
